"""Currency field added

Revision ID: a4cfe84d7ab1
Revises: e2fffd3b30e9
Create Date: 2023-10-03 13:46:22.519978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4cfe84d7ab1'
down_revision: Union[str, None] = 'e2fffd3b30e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('currency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'currency')
    # ### end Alembic commands ###
